services:
  - type: web
    name: bengo
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails db:migrate db:seed && bundle exec rails server -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: 193cd515fe52cc3dae4effbfc7b8caa0
    autoDeploy: true

databases:
  - name: bengo_db
