services:
  - type: web
    name: bengo
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    cpu: 0.25
    memory: 0.5GB
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: bengo
    databaseName: beno_db
    user: bengo
