default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: rails
  password: 12345678

development:
  <<: *default
  database: bengo_development

test:
  <<: *default
  database: bengo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>